[build]
  command = "pip install -r requirements.txt && python init_db.py"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.14"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
